// <Include>
///////////////////////////////////////////////////////////////////////////////
//
// THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT MODIFY IT BY HAND.
//
///////////////////////////////////////////////////////////////////////////////
// </Include>

// <LiteralInclude>
#include <wsdapi.h>
// </LiteralInclude>

// <LiteralInclude>
#include "FileServiceSecure.h"
// </LiteralInclude>

// <LiteralInclude>
#include "FileServiceSecureTypes.h"
// </LiteralInclude>

// <NamespaceDefinitions>
//
// Namespace http://www.example.com/ncd/FileServiceSecure
//
WSDXML_NAME Names_FileServiceSecure[] =
{   { &Namespace_FileServiceSecure, L"FileChangeEventType" }
,   { &Namespace_FileServiceSecure, L"GetFileRequest" }
,   { &Namespace_FileServiceSecure, L"GetFileResponse" }
,   { &Namespace_FileServiceSecure, L"GetFileListResponse" }
,   { &Namespace_FileServiceSecure, L"FileChangeEvent" }
,   { &Namespace_FileServiceSecure, L"FileServiceSecure" }
,   { &Namespace_FileServiceSecure, L"FileServiceSecure_GetFileList_InputMessage" }
,   { &Namespace_FileServiceSecure, L"FileServiceSecure_GetFileList_OutputMessage" }
,   { &Namespace_FileServiceSecure, L"GetFileList" }
,   { &Namespace_FileServiceSecure, L"FileList" }
,   { &Namespace_FileServiceSecure, L"Element" }
,   { &Namespace_FileServiceSecure, L"parameters" }
,   { &Namespace_FileServiceSecure, L"FileServiceSecure_GetFile_InputMessage" }
,   { &Namespace_FileServiceSecure, L"FileServiceSecure_GetFile_OutputMessage" }
,   { &Namespace_FileServiceSecure, L"GetFile" }
,   { &Namespace_FileServiceSecure, L"filePath" }
,   { &Namespace_FileServiceSecure, L"Attachment" }
,   { &Namespace_FileServiceSecure, L"FileServiceSecure_FileChangeEvent_OutputMessage" }
,   { &Namespace_FileServiceSecure, L"EventType" }
,   { &Namespace_FileServiceSecure, L"FileName" }
,   { &Namespace_FileServiceSecure, L"result" }
,   { &Namespace_FileServiceSecure, L"FileDeviceSecure" }
};
 WSDXML_NAMESPACE Namespace_FileServiceSecure =
{   L"http://www.example.com/ncd/FileServiceSecure"
,   L"fil"
,   &Names_FileServiceSecure[0]
,   22
,   0
};

//
// Namespace http://www.w3.org/2001/XMLSchema
//
WSDXML_NAME Names_XMLSchema[] =
{   { &Namespace_XMLSchema, L"anyType" }
};
 WSDXML_NAMESPACE Namespace_XMLSchema =
{   L"http://www.w3.org/2001/XMLSchema"
,   L"xm1"
,   &Names_XMLSchema[0]
,   1
,   1
};

WSDXML_NAMESPACE* FileServiceSecureNamespaces[] =
{   &Namespace_FileServiceSecure
,   &Namespace_XMLSchema
};

// </NamespaceDefinitions>

// <TypeTableDefinitions>
static BYTE TypeTable_GET_FILE_LIST_RESPONSE[] =
{   OpFormatPointerToStruct(GET_FILE_LIST_RESPONSE)
,   OpBeginSequence
,       OpAnyNumber
,           OpFormatListInsertTail(PWCHAR_LIST,GET_FILE_LIST_RESPONSE,FileList)
,               OpBeginElement(FILESERVICESECURE_FileList)
,                   OpFormatUnicodeString(PWCHAR_LIST,Element)
,               OpEndElement
,   OpEndSequence
,   OpEndOfTable
};
WSDXML_TYPE Type_GET_FILE_LIST_RESPONSE =
{   NULL
,   TypeTable_GET_FILE_LIST_RESPONSE
};

static BYTE TypeTable_GET_FILE_REQUEST[] =
{   OpFormatPointerToStruct(GET_FILE_REQUEST)
,   OpBeginSequence
,       OpBeginElement(FILESERVICESECURE_FilePath)
,           OpFormatUnicodeString(GET_FILE_REQUEST,filePath)
,       OpEndElement
,   OpEndSequence
,   OpEndOfTable
};
WSDXML_TYPE Type_GET_FILE_REQUEST =
{   NULL
,   TypeTable_GET_FILE_REQUEST
};

static BYTE TypeTable_GET_FILE_RESPONSE[] =
{   OpFormatPointerToStruct(GET_FILE_RESPONSE)
,   OpBeginSequence
,       OpBeginElement(FILESERVICESECURE_Attachment)
,           OpProcess(GET_FILE_RESPONSE,Attachment)
,           OpBeginElement(XOP_Include)
,               OpAttribute(XOP_Href)
,                   OpFormatUri(GET_FILE_RESPONSE,Attachment)
,           OpEndElement
,       OpEndElement
,   OpEndSequence
,   OpEndOfTable
};
WSDXML_TYPE Type_GET_FILE_RESPONSE =
{   NULL
,   TypeTable_GET_FILE_RESPONSE
};

static BYTE TypeTable_FILE_CHANGE_EVENT[] =
{   OpFormatPointerToStruct(FILE_CHANGE_EVENT)
,   OpBeginSequence
,       OpBeginElement(FILESERVICESECURE_EventType)
,           OpFormatUnicodeString(FILE_CHANGE_EVENT,EventType)
,       OpEndElement
,       OpBeginElement(FILESERVICESECURE_FileName)
,           OpFormatUnicodeString(FILE_CHANGE_EVENT,FileName)
,       OpEndElement
,   OpEndSequence
,   OpEndOfTable
};
WSDXML_TYPE Type_FILE_CHANGE_EVENT =
{   NULL
,   TypeTable_FILE_CHANGE_EVENT
};

WSDXML_TYPE* FileServiceSecureTypes[] =
{   &Type_GET_FILE_LIST_RESPONSE
,   &Type_GET_FILE_REQUEST
,   &Type_GET_FILE_RESPONSE
,   &Type_FILE_CHANGE_EVENT
};

// </TypeTableDefinitions>

// <MessageTypeDefinitions>
//
// Port type http://www.example.com/ncd/FileServiceSecure/FileServiceSecure
// Message type definitions
//
static BYTE RequestBodyType_GetFileList[] =
{   OpEndOfTable
};

WSDXML_TYPE REQUESTTYPE_GetFileList =
{   L"http://www.example.com/ncd/FileServiceSecure/GetFileList"
,   RequestBodyType_GetFileList
};

static BYTE ResponseBodyType_GetFileList[] =
{   OpFormatPointerToStruct(RESPONSEBODY_FileServiceSecure_GetFileList)
,   OpBeginElement(FILESERVICESECURE_GetFileListResponse)
,       OpFormatType(TYPE_ENCODING_GET_FILE_LIST_RESPONSE,RESPONSEBODY_FileServiceSecure_GetFileList,parameters)
,   OpEndElement
,   OpEndOfTable
};

WSDXML_TYPE RESPONSETYPE_GetFileList =
{   L"http://www.example.com/ncd/FileServiceSecure/GetFileListResponse"
,   ResponseBodyType_GetFileList
};

static BYTE RequestBodyType_GetFile[] =
{   OpFormatPointerToStruct(REQUESTBODY_FileServiceSecure_GetFile)
,   OpBeginElement(FILESERVICESECURE_GetFileRequest)
,       OpFormatType(TYPE_ENCODING_GET_FILE_REQUEST,REQUESTBODY_FileServiceSecure_GetFile,parameters)
,   OpEndElement
,   OpEndOfTable
};

WSDXML_TYPE REQUESTTYPE_GetFile =
{   L"http://www.example.com/ncd/FileServiceSecure/GetFile"
,   RequestBodyType_GetFile
};

static BYTE ResponseBodyType_GetFile[] =
{   OpFormatPointerToStruct(RESPONSEBODY_FileServiceSecure_GetFile)
,   OpBeginElement(FILESERVICESECURE_GetFileResponse)
,       OpFormatType(TYPE_ENCODING_GET_FILE_RESPONSE,RESPONSEBODY_FileServiceSecure_GetFile,parameters)
,   OpEndElement
,   OpEndOfTable
};

WSDXML_TYPE RESPONSETYPE_GetFile =
{   L"http://www.example.com/ncd/FileServiceSecure/GetFileResponse"
,   ResponseBodyType_GetFile
};

static BYTE ResponseBodyType_FileChangeEvent[] =
{   OpFormatPointerToStruct(RESPONSEBODY_FileServiceSecure_FileChangeEvent)
,   OpBeginElement(FILESERVICESECURE_FileChangeEvent)
,       OpFormatType(TYPE_ENCODING_FILE_CHANGE_EVENT,RESPONSEBODY_FileServiceSecure_FileChangeEvent,result)
,   OpEndElement
,   OpEndOfTable
};

WSDXML_TYPE RESPONSETYPE_FileChangeEvent =
{   L"http://www.example.com/ncd/FileServiceSecure/FileChangeEvent"
,   ResponseBodyType_FileChangeEvent
};


//
// Port type http://www.example.com/ncd/FileServiceSecure/FileDeviceSecure
// Message type definitions
//

// </MessageTypeDefinitions>

// <PortTypeDefinitions>
//
// Port type http://www.example.com/ncd/FileServiceSecure/FileServiceSecure
//
WSD_OPERATION Operations_FileServiceSecure[] =
{   {   &REQUESTTYPE_GetFileList
    ,   &RESPONSETYPE_GetFileList
    ,   (WSD_STUB_FUNCTION)Stub_GetFileList
    }
,   {   &REQUESTTYPE_GetFile
    ,   &RESPONSETYPE_GetFile
    ,   (WSD_STUB_FUNCTION)Stub_GetFile
    }
,   {   NULL
    ,   &RESPONSETYPE_FileChangeEvent
    ,   (WSD_STUB_FUNCTION)Stub_FileChangeEvent
    }
};

WSD_PORT_TYPE PortType_FileServiceSecure =
{   FILESERVICESECURE_FileServiceSecure
,   (sizeof(Operations_FileServiceSecure) / sizeof(Operations_FileServiceSecure[0]))
,   Operations_FileServiceSecure
,   WSD_PT_ALL
};

// </PortTypeDefinitions>

// <RelationshipMetadataDefinition>
static WSD_NAME_LIST serviceTypes_0[] =
{   {   NULL
    ,   &Names_FileServiceSecure[5] 
    }
};

static WSD_SERVICE_METADATA services_0[] =
{   {   NULL
    ,   &serviceTypes_0[0]
    ,   L"http://www.example.com/ncd/FileServiceSecure/FileServiceSecure0"
    ,   NULL
    }
};

static WSD_SERVICE_METADATA_LIST hostedServiceMetadataList_0[] =
{   {   NULL
    ,   &services_0[0]
    }
};

WSD_HOST_METADATA hostMetadata = 
{   
        NULL
    ,   hostedServiceMetadataList_0
};
// </RelationshipMetadataDefinition>

// <ThisModelMetadataDefinition>
static WSD_LOCALIZED_STRING modelNames[] =
{   {   NULL
    ,   L"Microsoft FileService Secure Device Emulator"
    }
};

static WSD_LOCALIZED_STRING_LIST modelNameList[] =
{   {   NULL
    ,   &modelNames[0]
    }
};

static WSD_LOCALIZED_STRING manufacturers[] =
{   {   NULL
    ,   L"Microsoft Corporation"
    }
};

static WSD_LOCALIZED_STRING_LIST manufacturerList[] =
{
    {   NULL
    ,   &manufacturers[0]
    },
};

WSD_THIS_MODEL_METADATA thisModelMetadata =
{   manufacturerList
,   L"http://www.microsoft.com/"
,   modelNameList
,   L"MFSDE-0002"
,   L"http://www.microsoft.com/"
,   L"http://www.microsoft.com/"
,   NULL // any
};
// </ThisModelMetadataDefinition>

