//
//  <copyright file="Resources.Designer.cs" company="Microsoft">
//    Copyright (C) Microsoft. All rights reserved.
//  </copyright>
//

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso.HostedEmail {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contoso.HostedEmail.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin@contoso.com.
        /// </summary>
        internal static string ContosoServices_DefaultAdminAccount {
            get {
                return ResourceManager.GetString("ContosoServices_DefaultAdminAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contoso Ltd..
        /// </summary>
        internal static string ContosoServices_DefaultCompanyName {
            get {
                return ResourceManager.GetString("ContosoServices_DefaultCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400-888-8888.
        /// </summary>
        internal static string ContosoServices_DefaultPhoneNumber {
            get {
                return ResourceManager.GetString("ContosoServices_DefaultPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email online service hosted by Contoso Ltd..
        /// </summary>
        internal static string ContosoServices_DefaultServiceName {
            get {
                return ResourceManager.GetString("ContosoServices_DefaultServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support@vip.contoso.com.
        /// </summary>
        internal static string ContosoServices_DefaultSupportEmail {
            get {
                return ResourceManager.GetString("ContosoServices_DefaultSupportEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTOSO.
        /// </summary>
        internal static string ContosoServices_DefaultTabDisplayName {
            get {
                return ResourceManager.GetString("ContosoServices_DefaultTabDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://protal.contoso.com.
        /// </summary>
        internal static string ContosoServices_DefaultUserPortal {
            get {
                return ResourceManager.GetString("ContosoServices_DefaultUserPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://contoso.com.
        /// </summary>
        internal static string ContosoServices_DefaultWebUrl {
            get {
                return ResourceManager.GetString("ContosoServices_DefaultWebUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is integrated with {0}.
        /// </summary>
        internal static string ContosoServices_IntegratedDescription {
            get {
                return ResourceManager.GetString("ContosoServices_IntegratedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is not integrated with {0}.
        /// </summary>
        internal static string ContosoServices_NotIntegratedDescription {
            get {
                return ResourceManager.GetString("ContosoServices_NotIntegratedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the admin account.
        /// </summary>
        internal static string ContosoServicesChangeAdminAccountTask_DisplayName {
            get {
                return ResourceManager.GetString("ContosoServicesChangeAdminAccountTask_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Contoso Services integration.
        /// </summary>
        internal static string ContosoServicesDisableServicesTask_DisplayName {
            get {
                return ResourceManager.GetString("ContosoServicesDisableServicesTask_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contoso Services Configuration Tab.
        /// </summary>
        internal static string ContosoServicesSubTab_Description {
            get {
                return ResourceManager.GetString("ContosoServicesSubTab_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string ContosoServicesSubTab_DisplayName {
            get {
                return ResourceManager.GetString("ContosoServicesSubTab_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessing information failed.
        /// </summary>
        internal static string ContosoServicesSubTab_ErrorDescription {
            get {
                return ResourceManager.GetString("ContosoServicesSubTab_ErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessing information....
        /// </summary>
        internal static string ContosoServicesSubTab_LoadingDescription {
            get {
                return ResourceManager.GetString("ContosoServicesSubTab_LoadingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string ContosoServicesSubTab_MailNumberDataString {
            get {
                return ResourceManager.GetString("ContosoServicesSubTab_MailNumberDataString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contoso Services Add-in.
        /// </summary>
        internal static string ContosoServicesTopLevelTab_Description {
            get {
                return ResourceManager.GetString("ContosoServicesTopLevelTab_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTOSO.
        /// </summary>
        internal static string ContosoServicesTopLevelTab_DisplayName {
            get {
                return ResourceManager.GetString("ContosoServicesTopLevelTab_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit my account online.
        /// </summary>
        internal static string ContosoServicesVisitMyAccountTask_DisplayName {
            get {
                return ResourceManager.GetString("ContosoServicesVisitMyAccountTask_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Group addin for Contoso Hosted Email.
        /// </summary>
        internal static string DGAdorner_Des {
            get {
                return ResourceManager.GetString("DGAdorner_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Group addin for Contoso Hosted Email.
        /// </summary>
        internal static string DGAdorner_Name {
            get {
                return ResourceManager.GetString("DGAdorner_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Groups.
        /// </summary>
        internal static string DGTab_Name {
            get {
                return ResourceManager.GetString("DGTab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no email account assigned to {0}..
        /// </summary>
        internal static string DGTab_NoEmailAccountMsg {
            get {
                return ResourceManager.GetString("DGTab_NoEmailAccountMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosted Email is already activated..
        /// </summary>
        internal static string ErrMsg_AlreadyActivated {
            get {
                return ResourceManager.GetString("ErrMsg_AlreadyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find adaptor configuration file {0}..
        /// </summary>
        internal static string ErrMsg_ConfigurationFileNotFound {
            get {
                return ResourceManager.GetString("ErrMsg_ConfigurationFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email account already exists..
        /// </summary>
        internal static string ErrMsg_OnlineUserAlreadyExist {
            get {
                return ResourceManager.GetString("ErrMsg_OnlineUserAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email account does not exist..
        /// </summary>
        internal static string ErrMsg_OnlineUserNotExist {
            get {
                return ResourceManager.GetString("ErrMsg_OnlineUserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save email account info..
        /// </summary>
        internal static string ErrorMsg_UpdateFailed {
            get {
                return ResourceManager.GetString("ErrorMsg_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already activated Office 365 subscriptions.
        /// </summary>
        internal static string ErrTitle_AlreadyActivated {
            get {
                return ResourceManager.GetString("ErrTitle_AlreadyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find adaptor configuration file..
        /// </summary>
        internal static string ErrTitle_ConfigurationFileNotFound {
            get {
                return ResourceManager.GetString("ErrTitle_ConfigurationFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email account already exists..
        /// </summary>
        internal static string ErrTitle_OnlineUserAlreadyExist {
            get {
                return ResourceManager.GetString("ErrTitle_OnlineUserAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email account does not exist..
        /// </summary>
        internal static string ErrTitle_OnlineUserNotExist {
            get {
                return ResourceManager.GetString("ErrTitle_OnlineUserNotExist", resourceCulture);
            }
        }
    }
}
