<!-- STANDARD MICROSOFT FOOTER FOR QUERY PAGES -->

<hr width=500 align=left>
<p>
<table border="0" cellpadding="0" cellspacing="0" width="500">
    <tr>
        <!-- IIS GIF -->
       <td>
            <a href="http://www.microsoft.com/Windows.NetServer"><img src="win2k.gif" alt="Learn more about Microsoft Windows"  border="0"></a>
        </td>

        <!-- Microsoft Legal Info -->
        <td align=center>
            <font style="font:arial; font-size: 8pt"> &copy;1997-2002 Microsoft Corporation. All rights reserved.<br></font>
            <a href="http://www.microsoft.com/misc/Info/cpyright.htm"><font style="font:arial; font-size: 6pt">Legal Notices.</font></a>
       </td>

        <!-- Best with IE GIF -->
        <td align=right>
            <a href="http://www.microsoft.com/ie"><img src="IE.GIF" alt="Download Internet Explorer!"  border="0"></a>
        </td>
    </tr>
</table>
