<td valign="top" align="left" height="28"><!--webbot bot="ImageMap"
rectangle="(420,1) (515, 18)  rtk.htm" rectangle="(350,1) (415, 19)  interopt.htm"
rectangle="(233,1) (345, 19)  ad.htm" rectangle="(165,1) (223, 19)  winnt.htm"
rectangle="(67,1) (165, 19)  dev.htm" rectangle="(13,1) (65, 20)  default.htm"
src="router.gif" alt="router.gif (3874 bytes)" border="0" startspan --><MAP NAME="FrontPageMap"><AREA SHAPE="RECT" COORDS="420, 1, 515, 18" HREF="rtk.htm"><AREA SHAPE="RECT" COORDS="350, 1, 415, 19" HREF="interopt.htm"><AREA SHAPE="RECT" COORDS="233, 1, 345, 19" HREF="ad.htm"><AREA SHAPE="RECT" COORDS="165, 1, 223, 19" HREF="winnt.htm"><AREA SHAPE="RECT" COORDS="67, 1, 165, 19" HREF="dev.htm"><AREA SHAPE="RECT" COORDS="13, 1, 65, 20" HREF="default.htm"></MAP><a href="../_vti_bin/shtml.dll/sdk/dq.htm/map"><img src="router.gif" alt="router.gif (3874 bytes)" border="0" ismap width="536" height="26" usemap="#FrontPageMap"></a><!--webbot bot="ImageMap" endspan i-checksum="31120" --></td>
<td width="3%" height="28"></td>
<td width="21%" height="28"></td>
